!!python/object/new:dynamic_reconfigure.encoding.Config
dictitems:
  acc_lim_theta: 2.0
  acc_lim_x: 0.5
  acc_lim_y: 0.0
  acc_limit_trans: 0.1
  angular_sim_granularity: 0.1
  forward_point_distance: 0.325
  goal_distance_bias: 24.0
  groups: !!python/object/new:dynamic_reconfigure.encoding.Config
    dictitems:
      acc_lim_theta: 2.0
      acc_lim_x: 0.5
      acc_lim_y: 0.0
      acc_limit_trans: 0.1
      angular_sim_granularity: 0.1
      forward_point_distance: 0.325
      goal_distance_bias: 24.0
      groups: !!python/object/new:dynamic_reconfigure.encoding.Config
        state: []
      id: 0
      max_rot_vel: 1.0
      max_scaling_factor: 0.2
      max_trans_vel: 0.5
      max_vel_x: 2.0
      max_vel_y: 0.0
      min_rot_vel: 0.4
      min_trans_vel: 0.1
      min_vel_x: 0.0
      min_vel_y: 0.0
      name: Default
      occdist_scale: 0.5
      oscillation_reset_angle: 0.2
      oscillation_reset_dist: 0.05
      parameters: !!python/object/new:dynamic_reconfigure.encoding.Config
        state: []
      parent: 0
      path_distance_bias: 40.0
      prune_plan: false
      restore_defaults: false
      rot_stopped_vel: 0.4
      scaling_speed: 0.25
      sim_granularity: 0.025
      sim_time: 2.0
      state: true
      stop_time_buffer: 0.2
      trans_stopped_vel: 0.1
      twirling_scale: 0.0
      type: ''
      use_dwa: true
      vth_samples: 20
      vx_samples: 6
      vy_samples: 1
      xy_goal_tolerance: 0.3
      yaw_goal_tolerance: 6.28
    state: []
  max_rot_vel: 1.0
  max_scaling_factor: 0.2
  max_trans_vel: 0.5
  max_vel_x: 2.0
  max_vel_y: 0.0
  min_rot_vel: 0.4
  min_trans_vel: 0.1
  min_vel_x: 0.0
  min_vel_y: 0.0
  occdist_scale: 0.5
  oscillation_reset_angle: 0.2
  oscillation_reset_dist: 0.05
  path_distance_bias: 40.0
  prune_plan: false
  restore_defaults: false
  rot_stopped_vel: 0.4
  scaling_speed: 0.25
  sim_granularity: 0.025
  sim_time: 1.0
  stop_time_buffer: 0.2
  trans_stopped_vel: 0.1
  twirling_scale: 0.0
  use_dwa: true
  vth_samples: 20
  vx_samples: 6
  vy_samples: 1
  xy_goal_tolerance: 0.8
  yaw_goal_tolerance: 6.28
state: []
